- hosts: frontend
  become: yes
  become_user: root

  tasks:
    - name: Instalar Apache httpd rpm
      yum: name=httpd update_cache=yes 

    - name: Iniciar el servicio httpd
      systemd: name=httpd state=started enabled=yes
