- hosts: frontend
  become: yes
  tasks:
    - name: Asegurar que los repositorios esten actualizados
      shell: "{{item}}"
      with_items:
        - "subscription-manager register --username usuario --password clave --auto-attach --force"
      when: ansible_distribution == 'RedHat'

    - name: Instalar Apache httpd rpm
      yum: name=httpd update_cache=yes

    - name: Iniciar el servicio httpd
      systemd: name=httpd state=started enabled=yes

    - name: Asegurar que httpd exponga el puerto correcto
      lineinfile:
        dest: "/etc/httpd/conf/httpd.conf"
        regexp: "^Listen 80$"
        line: "Listen 4041"
        state: "present"
        backrefs: yes

    - name: Reiniciar el servicio httpd
      systemd: name=httpd state=restarted daemon_reload=yes

    - name: Instalar unzip
      yum: name=unzip update_cache=yes
