- hosts: frontend
  become: yes

  tasks:
    # Instalar apache
    - name: install apache
      yum: name=httpd update_cache=yes state=latest
    # Iniciar apache
    - name: start apache
      systemd: name=httpd state=started enable=yes

    - name: Asegurar que selinux este deshabilitado  # Necesario para cambiar el puerto de apache
      selinux: state=permissive policy=targeted

    - name: Asegurar que httpd exponga el puerto correcto
      lineinfile:
        dest: "/etc/httpd/conf/httpd.conf"
        regexp: '^Listen 80$'
        line: 'Listen {{apache_puerto}}'
        state: 'present'
        backrefs: yes

    # Reiniciar apache
    - name: restart apache
      systemd: name=httpd state=restart enable=yes

- hosts: desplegar
  become: yes

  tasks:
    # Copiar los archivos